# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_fix_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accountdeletion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='signupcode',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='signupcoderesult',
            name='signup_code',
        ),
        migrations.RemoveField(
            model_name='signupcoderesult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountDeletion',
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
        migrations.DeleteModel(
            name='SignupCode',
        ),
        migrations.DeleteModel(
            name='SignupCodeResult',
        ),
    ]
