# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [(b'project', '0002_auto_20151230_0359')]

    initial = True

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expert',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
