# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_text', models.CharField(max_length=30, verbose_name=b'First Name')),
                ('last_name_text', models.CharField(max_length=30, verbose_name=b'Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_text', models.CharField(max_length=30, verbose_name=b'First Name')),
                ('last_name_text', models.CharField(max_length=30, verbose_name=b'Last Name')),
                ('description_text', models.CharField(max_length=200, verbose_name=b'Description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('info_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('end_date', models.DateTimeField(verbose_name=b'date end')),
                ('state', models.CharField(choices=[(b'PC', b'Project is created'), (b'PS', b'Project is submitted'), (b'EA', b'An expert is assigned'), (b'IP', b'An expert is working on it'), (b'PF', b'Project is finished'), (b'PR', b'Payment is received and the project is closed')], default=b'PC', max_length=2)),
                ('assgin_to', models.CharField(choices=[(b'PC', b'Project is created'), (b'PS', b'Project is submitted'), (b'EA', b'An expert is assigned'), (b'IP', b'An expert is working on it'), (b'PF', b'Project is finished'), (b'PR', b'Payment is received and the project is closed')], default=b'CLT', max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.Client')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.Expert')),
            ],
        ),
    ]
