# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=b'12345', max_length=30, verbose_name=b'Password'),
        ),
        migrations.AddField(
            model_name='expert',
            name='password',
            field=models.CharField(default=datetime.datetime(2015, 12, 20, 3, 28, 0, 764406, tzinfo=utc), max_length=30, verbose_name=b'Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[(b'A', b'Expert is applying'), (b'J', b'Expert'), (b'S', b'Senior Expert')], default=b'A', max_length=1),
        ),
        migrations.AlterField(
            model_name='expert',
            name='description_text',
            field=models.CharField(max_length=500, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assgin_to',
            field=models.CharField(choices=[(b'CLT', b'Waiting for client'), (b'EPT', b'Waiting for expert'), (b'ADM', b'Waiting for system administrator')], default=b'CLT', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='info_text',
            field=models.CharField(max_length=500),
        ),
    ]
