# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_auto_20151220_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='password',
            field=models.CharField(default=b'12345', max_length=30, verbose_name=b'Password'),
        ),
    ]
