# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 19:12
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=255)),
                ('project_id', models.IntegerField(default=0)),
                ('avatar', models.FileField(blank=True, upload_to=common.models.ProjectFile.get_file_path, verbose_name='Avatar')),
            ],
        ),
    ]
