# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_accounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_text', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name_text', models.CharField(max_length=30, verbose_name='Last Name')),
                ('password', models.CharField(default='12345', max_length=30, verbose_name='Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_text', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name_text', models.CharField(max_length=30, verbose_name='Last Name')),
                ('password', models.CharField(default='12345', max_length=30, verbose_name='Password')),
                ('description_text', models.CharField(max_length=500, verbose_name='Description')),
                ('status', models.CharField(choices=[('A', 'Expert is applying'), ('J', 'Expert'), ('S', 'Senior Expert')], default='A', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('info_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('state', models.CharField(choices=[('PC', 'Project is created'), ('PS', 'Project is submitted'), ('EA', 'An expert is assigned'), ('IP', 'An expert is working on it'), ('PF', 'Project is finished'), ('PR', 'Payment is received and the project is closed')], default='PC', max_length=2)),
                ('assgin_to', models.CharField(choices=[('CLT', 'Waiting for client'), ('EPT', 'Waiting for expert'), ('ADM', 'Waiting for system administrator')], default='CLT', max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Client')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Expert')),
            ],
        ),
    ]
