# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_client_expert_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expert',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='Client', max_length=30, verbose_name='Account Type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
