# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160221_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='description_text',
            field=models.CharField(max_length=500, verbose_name='Summary'),
        ),
    ]
