# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 02:56
from __future__ import unicode_literals

import common.multichoice
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160226_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='industry_multi',
            field=common.multichoice.MultiSelectField(blank=True, choices=[('MC', 'Management Consulting'), ('EN', 'Energy'), ('HI', 'Health care and Life Sciences'), ('BI', 'BioPharma'), ('ED', 'Education'), ('SE', 'Semiconductor'), ('SW', 'Software'), ('MB', 'Mobile Internet and Computing'), ('DS', 'Data and Storage'), ('VR', 'VR/AI/Robotics'), ('IT', 'Internet of Things'), ('GB', 'Gaming and Media'), ('ET', 'Entertainment'), ('TL', 'Transport and Logistics'), ('AU', 'Automotive'), ('CG', 'Consumer Goods'), ('OT', 'Others')], max_length=250),
        ),
    ]
