# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 06:25
from __future__ import unicode_literals

import common.multichoice
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_expert_industry_multi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='industry_multi',
            new_name='industries',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='industry',
        ),
        migrations.AlterField(
            model_name='expert',
            name='expertise',
            field=common.multichoice.MultiSelectField(blank=True, choices=[('ST', 'Strategy'), ('BD', 'Business Development and Sales'), ('SP', 'Strategic Partnership'), ('MK', 'Marketing'), ('MT', 'Market Research'), ('OS', 'Operations and Supply Chain'), ('MA', 'Merger and Acquisition'), ('DA', 'Data Analytics'), ('SE', 'Software Engineering'), ('PJ', 'Project Management'), ('PD', 'Product Design and Development'), ('PM', 'Product Management'), ('EN', 'Entrepreneurship'), ('CS', 'Corporate Strategy'), ('CC', 'Cloud Computing'), ('AD', 'Advertisement'), ('CL', 'Corporate Law'), ('CF', 'Corporate Finance'), ('AT', 'Accounting and Taxation'), ('OT', 'Others')], max_length=250),
        ),
    ]
