# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_expert_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='area',
            field=models.CharField(choices=[('BJ', 'Beijing'), ('SF', 'San Francisco'), ('SN', 'Singapore')], default='BJ', max_length=2),
        ),
        migrations.AddField(
            model_name='expert',
            name='experience',
            field=models.CharField(choices=[('A', '1-5 years'), ('B', '5-10 years'), ('C', '10-15 years'), ('D', '>15 years')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='expert',
            name='expertise',
            field=models.CharField(choices=[('MC', 'Management Consulting'), ('EN', 'Entrepreneurship'), ('CS', 'Corporate Strategy'), ('BD', 'Business Development'), ('PM', 'Product Management'), ('MA', 'Merger and Acquisition'), ('SM', 'Sales and Marketing'), ('LS', 'Legal Services'), ('FA', 'Finance and Accounting'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='expert',
            name='industry',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('MB', 'Mobile Internet'), ('SW', 'Software and Database System'), ('HW', 'Hardware and Storage'), ('BI', 'Biotech'), ('LS', 'Life Science'), ('CS', 'Consulting Services'), ('PE', 'Power and Energy'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='assign_history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='info_text',
            field=models.TextField(),
        ),
    ]
