# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userprofile_avatar'),
        ('common', '0007_auto_20160228_0625'),
    ]

    operations = [
    ]
