# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20160109_2028'),
        ('common', '0007_auto_20160110_0126'),
    ]

    operations = [
    ]
