# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 09:03
from __future__ import unicode_literals

import common.multichoice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20160228_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='area',
            field=models.CharField(choices=[('US', 'United States'), ('CN', 'China'), ('SG', 'Singapore'), ('JP', 'Japan'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expertise',
            field=common.multichoice.MultiSelectField(blank=True, choices=[('ST', 'Strategy'), ('BD', 'Business Development and Sales'), ('SP', 'Strategic Partnership'), ('MK', 'Marketing'), ('MT', 'Market Research'), ('OS', 'Operations and Supply Chain'), ('MA', 'Merger and Acquisition'), ('DA', 'Data Analytics'), ('SE', 'Software Engineering'), ('PJ', 'Project Management'), ('PD', 'Product Design and Development'), ('PM', 'Product Management'), ('EN', 'Entrepreneurship'), ('CS', 'Corporate Strategy'), ('CC', 'Cloud Computing'), ('AD', 'Advertisement'), ('CL', 'Corporate Law'), ('CF', 'Corporate Finance'), ('AT', 'Accounting and Taxation'), ('OT', 'Other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='expert',
            name='industries',
            field=common.multichoice.MultiSelectField(blank=True, choices=[('MC', 'Management Consulting'), ('EN', 'Energy'), ('HI', 'Health care and Life Sciences'), ('BI', 'BioPharma'), ('ED', 'Education'), ('SE', 'Semiconductor'), ('SW', 'Software'), ('MB', 'Mobile Internet and Computing'), ('DS', 'Data and Storage'), ('VR', 'VR/AI/Robotics'), ('IT', 'Internet of Things'), ('GB', 'Gaming and Media'), ('ET', 'Entertainment'), ('TL', 'Transport and Logistics'), ('AU', 'Automotive'), ('CG', 'Consumer Goods'), ('OT', 'Other')], max_length=250),
        ),
    ]
