# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20160114_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expert_pref_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='expertise',
            field=models.CharField(choices=[('MC', 'Management Consulting'), ('EN', 'Entrepreneurship'), ('CS', 'Corporate Strategy'), ('BD', 'Business Development'), ('PM', 'Product Management'), ('MA', 'Merger and Acquisition'), ('SM', 'Sales and Marketing'), ('LS', 'Legal Services'), ('FA', 'Finance and Accounting'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('MB', 'Mobile Internet'), ('SW', 'Software and Database System'), ('HW', 'Hardware and Storage'), ('BI', 'Biotech'), ('LS', 'Life Science'), ('CS', 'Consulting Services'), ('PE', 'Power and Energy'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='rate_type',
            field=models.CharField(choices=[('F', 'Fixed amount'), ('H', 'Hourly rate')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.CharField(choices=[('D', 'Deep dive'), ('G', 'General advisory')], default='G', max_length=1),
        ),
    ]
