# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 07:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20160114_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='education',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='expert',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cell_phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('PC', 'Project is created'), ('PS', 'Project is submitted'), ('EA', 'An expert is assigned'), ('ET', 'An expert took this project'), ('CA', 'The client accepted this expert'), ('IP', 'An expert is working on it'), ('PF', 'Project is finished'), ('CC', 'The client has confirmed the project finish'), ('AD', 'The client has appealed the dispute to the administrator'), ('PR', 'Payment is received and the project is closed')], default='PC', max_length=2),
        ),
        migrations.AddField(
            model_name='commentforexpert',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Expert'),
        ),
        migrations.AddField(
            model_name='commentforexpert',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project'),
        ),
    ]
