# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_commentforexpert_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentforexpert',
            name='expert',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='common.Expert'),
            preserve_default=False,
        ),
    ]
