# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20160213_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='education',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
